In [1]:
import torch

In [ ]:
a = torch.tensor([0, 1, 2])
a

tensor([1, 2, 3])

In [17]:
b = torch.arange(0, 9).reshape(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
(a @ b.transpose(0, 1))

tensor([ 8, 26, 44])

In [26]:
print(torch.sum(a * b, dim=-1))

tensor([ 8, 26, 44])
